language: node_js
node_js:
  - '10'

before_install:
  - npm i -g npm@6.9.0
  
notifications:
  email: false

services:
  - postgresql

before_script:
  - npm install
  - psql -c 'create database teamwork;' -U postgres

script:
- npm run test

env:
  global:
    - adminToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsYXVkQGFkbWluLnR3IiwiaWQiOjEwLCJhZG1pbiI6InRydWUiLCJpYXQiOjE1NzQ5OTIzNzQsImV4cCI6MTU3NTI1MTU3NH0.RTT4pCalwjIIB59hy_4Rn5LtU3XDoppvsFuZMDseEZ8

    